coverage:
  status:
    project:
      default:
        target: 88%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 80%
        informational: false

comment:
  layout: "diff, files"
  behavior: default
  require_changes: true
